common:
  limitRate: true

server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: andy-springboot4-template
  data:
    mongodb:
      auto-index-creation: false # disable auto index creation explicitly as we choose to manage indexes using Mongock
  profiles:
    active: local # use "local" profile by default for local run
  cache:
    type: redis
  threads:
    virtual:
      enabled: true
  kafka:
    template:
      observation-enabled: true
    listener:
      observation-enabled: true

mongock:
  enabled: true
  migration-scan-package: com.company.andy.common.migration
  transactional: true
  lock-repository-name: mongock-lock
  migration-repository-name: mongock-migration

springdoc:
  default-produces-media-type: application/json
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
    tags-sorter: alpha
    operations-sorter: method

management:
  tracing:
    sampling:
      probability: 1.0
  defaults:
    metrics:
      export:
        enabled: false